---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates (OracleLinux)
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: install updates (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks: 

  - name: install httpd and php packages for OracleLinux
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (OracleLinux)
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: install mariadb package (Ubuntu)
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package (OracleLinux and Ubuntu)
    package:
      name: samba
      state: latest
